--------------------------------------------------------
-- Archivo creado  - viernes-octubre-13-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ANSWERS
--------------------------------------------------------
---PUNTO 1 AL 5

CREATE TABLESPACE CURSOS datafile 
'courses1.dbf' SIZE 50M
AUTOEXTEND ON NEXT 100K MAXSIZE 500M
EXTENT MANAGEMENT LOCAL 
SEGMENT SPACE MANAGEMENT AUTO
ONLINE
;


CREATE PROFILE administrativo limit SESSIONS_PER_USER 1
IDLE_TIME 25 FAILED_LOGIN_ATTEMPTS 4 ;

CREATE USER garroyave
IDENTIFIED BY garroya123
DEFAULT TABLESPACE CURSOS
QUOTA 30m ON CURSOS
PROFILE administrativo;


GRANT DBA TO garroyave;
GRANT CONNECT, RESOURCE TO DBA;


  CREATE TABLE "GARROYAVE"."ANSWERS" 
   (	"ID" NUMBER(*,0), 
	"NUMBER_OF_QUESTION" VARCHAR2(255 BYTE), 
	"ANSWER" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CURSOS" ;
--------------------------------------------------------
--  DDL for Table ATTENDANCE
--------------------------------------------------------

  CREATE TABLE "GARROYAVE"."ATTENDANCE" 
   (	"ID" NUMBER(*,0), 
	"STUDENT_ID" NUMBER(*,0), 
	"COURSE_ID" NUMBER(*,0), 
	"ATTENDANCE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CURSOS" ;
--------------------------------------------------------
--  DDL for Table COURSE
--------------------------------------------------------

  CREATE TABLE "GARROYAVE"."COURSE" 
   (	"ID" NUMBER(*,0), 
	"NAME" VARCHAR2(255 BYTE), 
	"CODE" VARCHAR2(255 BYTE), 
	"DATE_START" DATE, 
	"DATE_END" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CURSOS" ;
--------------------------------------------------------
--  DDL for Table STUDENTS
--------------------------------------------------------

  CREATE TABLE "GARROYAVE"."STUDENTS" 
   (	"ID" NUMBER(*,0), 
	"FIRST_NAME" VARCHAR2(255 BYTE), 
	"LAST_NAME" VARCHAR2(255 BYTE), 
	"DATE_OF_BIRTH" DATE, 
	"CITY" VARCHAR2(255 BYTE), 
	"ADRRESS" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CURSOS" ;
REM INSERTING into GARROYAVE.ANSWERS
SET DEFINE OFF;
REM INSERTING into GARROYAVE.ATTENDANCE
SET DEFINE OFF;
REM INSERTING into GARROYAVE.COURSE
SET DEFINE OFF;
REM INSERTING into GARROYAVE.STUDENTS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index SYS_C007013
--------------------------------------------------------

  CREATE UNIQUE INDEX "GARROYAVE"."SYS_C007013" ON "GARROYAVE"."ANSWERS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CURSOS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007018
--------------------------------------------------------

  CREATE UNIQUE INDEX "GARROYAVE"."SYS_C007018" ON "GARROYAVE"."ATTENDANCE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CURSOS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007002
--------------------------------------------------------

  CREATE UNIQUE INDEX "GARROYAVE"."SYS_C007002" ON "GARROYAVE"."COURSE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CURSOS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007009
--------------------------------------------------------

  CREATE UNIQUE INDEX "GARROYAVE"."SYS_C007009" ON "GARROYAVE"."STUDENTS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CURSOS" ;
--------------------------------------------------------
--  Constraints for Table ANSWERS
--------------------------------------------------------

  ALTER TABLE "GARROYAVE"."ANSWERS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CURSOS"  ENABLE;
  ALTER TABLE "GARROYAVE"."ANSWERS" MODIFY ("ANSWER" NOT NULL ENABLE);
  ALTER TABLE "GARROYAVE"."ANSWERS" MODIFY ("NUMBER_OF_QUESTION" NOT NULL ENABLE);
  ALTER TABLE "GARROYAVE"."ANSWERS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ATTENDANCE
--------------------------------------------------------

  ALTER TABLE "GARROYAVE"."ATTENDANCE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CURSOS"  ENABLE;
  ALTER TABLE "GARROYAVE"."ATTENDANCE" MODIFY ("ATTENDANCE_DATE" NOT NULL ENABLE);
  ALTER TABLE "GARROYAVE"."ATTENDANCE" MODIFY ("COURSE_ID" NOT NULL ENABLE);
  ALTER TABLE "GARROYAVE"."ATTENDANCE" MODIFY ("STUDENT_ID" NOT NULL ENABLE);
  ALTER TABLE "GARROYAVE"."ATTENDANCE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COURSE
--------------------------------------------------------

  ALTER TABLE "GARROYAVE"."COURSE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CURSOS"  ENABLE;
  ALTER TABLE "GARROYAVE"."COURSE" MODIFY ("DATE_END" NOT NULL ENABLE);
  ALTER TABLE "GARROYAVE"."COURSE" MODIFY ("DATE_START" NOT NULL ENABLE);
  ALTER TABLE "GARROYAVE"."COURSE" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "GARROYAVE"."COURSE" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "GARROYAVE"."COURSE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STUDENTS
--------------------------------------------------------

  ALTER TABLE "GARROYAVE"."STUDENTS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CURSOS"  ENABLE;
  ALTER TABLE "GARROYAVE"."STUDENTS" MODIFY ("ADRRESS" NOT NULL ENABLE);
  ALTER TABLE "GARROYAVE"."STUDENTS" MODIFY ("CITY" NOT NULL ENABLE);
  ALTER TABLE "GARROYAVE"."STUDENTS" MODIFY ("DATE_OF_BIRTH" NOT NULL ENABLE);
  ALTER TABLE "GARROYAVE"."STUDENTS" MODIFY ("LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "GARROYAVE"."STUDENTS" MODIFY ("FIRST_NAME" NOT NULL ENABLE);
  ALTER TABLE "GARROYAVE"."STUDENTS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ATTENDANCE
--------------------------------------------------------

  ALTER TABLE "GARROYAVE"."ATTENDANCE" ADD CONSTRAINT "FK_COURSE_ID" FOREIGN KEY ("COURSE_ID")
	  REFERENCES "GARROYAVE"."COURSE" ("ID") ENABLE;
  ALTER TABLE "GARROYAVE"."ATTENDANCE" ADD CONSTRAINT "FK_STUDENTS_ID" FOREIGN KEY ("STUDENT_ID")
	  REFERENCES "GARROYAVE"."STUDENTS" ("ID") ENABLE;
